package org.mmpp.impruth.model;

// Generated 2011/02/12 22:05:41 by Hibernate Tools 3.2.4.GA

import org.mmpp.simplelogin.model.User;

/**
 * OwnBook generated by hbm2java
 */
public class OwnBook implements java.io.Serializable {

	private User user;
	private String barcode;

	public OwnBook() {
	}

	public OwnBook(User user, String barcode) {
		this.user = user;
		this.barcode = barcode;
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

}
