package org.mmpp.impruth.model;

// Generated 2011/02/14 21:37:58 by Hibernate Tools 3.2.4.GA

import org.mmpp.simplelogin.model.User;

/**
 * OwnBook generated by hbm2java
 */
public class OwnBook implements java.io.Serializable {

	private int userId;
	private String barcode;
	private User user;


	public OwnBook(){
		
	}
	public OwnBook(int userId, String barcode) {
		this.userId = userId;
		this.barcode = barcode;
	}


	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
