package org.mmpp.simplelogin.model;

// Generated 2011/02/24 21:32:15 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.mmpp.impruth.model.ReleaseInformation;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String emailAddress;
	private String password;
	private String firstName;
	private String lastName;
	private String organization;
	private boolean notification;
	private Set<ReleaseInformation> books = new HashSet<ReleaseInformation>(0);

	public User() {
	}

	public User(String emailAddress, String password) {
		this.emailAddress = emailAddress;
		this.password = password;
	}

	public User(String emailAddress, String password, String firstName,
			String lastName, String organization, boolean notification,
			Set<ReleaseInformation> books) {
		this.emailAddress = emailAddress;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.organization = organization;
		this.notification = notification;
		this.books = books;
	}

	public int getId() {
		return this.id;
	}

	protected void setId(int id) {
		this.id = id;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public boolean isNotification() {
		return this.notification;
	}

	public void setNotification(boolean notification) {
		this.notification = notification;
	}

	public Set<ReleaseInformation> getBooks() {
		return this.books;
	}

	public void setBooks(Set<ReleaseInformation> books) {
		this.books = books;
	}

}
