package org.mmpp.simplelogin.model;

// Generated 2011/02/16 15:45:43 by Hibernate Tools 3.2.4.GA

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private String emailAddress;
	private String password;
	private String firstName;
	private String lastName;
	private String organization;
	private boolean notification;

	public User() {
	}

	public User(String emailAddress, String password) {
		this.emailAddress = emailAddress;
		this.password = password;
	}

	public User(String emailAddress, String password, String firstName,
			String lastName, String organization, boolean notification) {
		this.emailAddress = emailAddress;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.organization = organization;
		this.notification = notification;
	}

	public int getId() {
		return this.id;
	}

	protected void setId(int id) {
		this.id = id;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public boolean isNotification() {
		return this.notification;
	}

	public void setNotification(boolean notification) {
		this.notification = notification;
	}

}
