package org.mmpp.impruth.model;

// Generated 2011/02/24 21:32:15 by Hibernate Tools 3.4.0.CR1

/**
 * Media generated by hbm2java
 */
public class Media implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String title;
	private String subtitle;
	private String pretitle;
	private int volume;
	private String volumeValue;

	public Media() {
	}

	public Media(String title) {
		this.title = title;
	}

	public Media(String title, String subtitle, String pretitle, int volume,
			String volumeValue) {
		this.title = title;
		this.subtitle = subtitle;
		this.pretitle = pretitle;
		this.volume = volume;
		this.volumeValue = volumeValue;
	}

	public int getId() {
		return this.id;
	}

	protected void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public String getPretitle() {
		return this.pretitle;
	}

	public void setPretitle(String pretitle) {
		this.pretitle = pretitle;
	}

	public int getVolume() {
		return this.volume;
	}

	public void setVolume(int volume) {
		this.volume = volume;
	}

	public String getVolumeValue() {
		return this.volumeValue;
	}

	public void setVolumeValue(String volumeValue) {
		this.volumeValue = volumeValue;
	}

}
